service: api-hyper-core

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 1024
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    PORT: 3000
    CHAIN_ID: 999
    INTENT_CHUNK_SIZE: ${env:INTENT_CHUNK_SIZE, '10'}
    RPC_URL_HYPEREVM: ${env:RPC_URL_HYPEREVM, 'https://rpc.hyperliquid.xyz/evm'}
    SIGNER_PRIVATE_KEY_MAP: ${env:SIGNER_PRIVATE_KEY_MAP, ''}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
  apiGateway:
    apiKeys:
      - apiHyperCoreKey # x-api-key header value

functions:
  api:
    handler: dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          private: true
      - http:
          path: /
          method: ANY
          private: true

package:
  include:
    - dist/**
    - node_modules/**
    - package.json
  exclude:
    - src/**
    - node_modules/.bin/**
    - test/**
    - tests/**
    - README.md
    - .gitignore
    - .git/**
    - .env

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3009
    host: 0.0.0.0
  dotenv:
    path: .env
    basePath: ./
    logging: false

resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:service}-${self:provider.stage}-ApiGatewayRestApiId
    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:service}-${self:provider.stage}-ApiGatewayRestApiRootResourceId
    ApiGatewayUrl:
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - ${self:provider.region}
            - ".amazonaws.com/"
            - ${self:provider.stage}
      Export:
        Name: ${self:service}-${self:provider.stage}-ApiGatewayUrl
