/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UserProxyContract } from "./UserProxyContract";
export type { UserProxyFactory } from "./UserProxyFactory";
export * as factories from "./factories";
export { UserProxyContract__factory } from "./factories/UserProxyContract__factory";
export { UserProxyFactory__factory } from "./factories/UserProxyFactory__factory";
