/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UserProxyContract__factory } from "./UserProxyContract__factory";
export { UserProxyFactory__factory } from "./UserProxyFactory__factory";
